version: '3.8'

services:
  # Development service
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app  # Mount the project directory
      - /app/node_modules  # Ensure the host node_modules isn't used
    profiles:
      - dev  # Profile to enable development-specific settings
